# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXCSzvMXU-5_j9v_FYP7kus606d7P-S1
"""

!pip install pytesseract
!pip install pillow
!sudo apt install tesseract-ocr # Install Tesseract OCR engine

import pytesseract
from PIL import Image

# OCR motorini o'rnatish yo'li (o'z tizimingizga moslash)
pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'  # Tesseract yo'lini o'zingizga moslang

# Rasmni ochish
rasm = Image.open('photo_2024-11-28_16-17-22.jpg')

# Rasmdagi matnni chiqarish
matn = pytesseract.image_to_string(rasm)
print("Rasmdagi matn:")
print(matn)